---
title: 'COVID-19  Dashboard:Cox’s Bazar, Bangladesh'
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: bootstrap
editor_options: 
  chunk_output_type: console
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, error=TRUE)
```

```{r setup_import, include=FALSE}
##Load required packages
pacman::p_load(here, data.table, janitor, linelist,dplyr,lubridate,tidyr,purrr,furrr,forcats,stringr,ggthemes,gt,   RcppRoll,scales,sf,patchwork,flexdashboard,plotly,ggupset,table1,ggpubr,googlesheets4,httr,jsonlite,leaflet,tsibble,DT,tidyjson,wesanderson)
```

```{r, include=FALSE}
source_fn <- function(x) {
  source(x, local = knitr::knit_global())
}

list_setup <- list.files(here('modules'), full.names=T, pattern=".R")
list_sections <- list.files(here('modules', 'sections'), full.names=T)

purrr::map(list_setup,source_fn)

source("modules/sections/1_landing_page.R", local = knitr::knit_global())
source("modules/sections/2_host_community.R", local = knitr::knit_global())
source("modules/sections/3_fdmn_rohingya.R", local = knitr::knit_global())
source("modules/sections/4_epidemiology.R", local = knitr::knit_global())
source("modules/sections/5_testing.R", local = knitr::knit_global())
source("modules/sections/6_cbs.R", local = knitr::knit_global())
source("modules/sections/7_ewars_deaths.R", local = knitr::knit_global())
source("modules/sections/8_ccm.R", local = knitr::knit_global())
source("modules/sections/9_quarantine.R", local = knitr::knit_global())
#plan(multiprocess)
#furrr::future_map(list_sections,source_fn)
```

Landing page
=====================================  

```{r child=here::here("modules","rmds","1_landing_page.Rmd")}
```

Host community  {data-orientation=columns}
=====================================  

```{r child=here::here("modules","rmds","2_host.Rmd")}
```

Rohingya refugee/FDMN {data-orientation=columns}
=====================================  

```{r child=here::here("modules","rmds","3_fdmn.Rmd")}
```

Epidemiology {data-orientation=columns}
=====================================  

```{r child=here::here("modules","rmds","4_epidemiology.Rmd")}
```

Testing {data-orientation=row}
=====================================  

```{r child=here::here("modules","rmds","5_testing.Rmd")}
```

EWARS - Overall {data-navmenu="All-cause mortality"}  
=====================================  

```{r child=here::here("modules","rmds","6_ewars.Rmd")}
```

Community-based surveillance 
=====================================  

```{r child=here::here("modules","rmds","7_cbs.Rmd")}
```

Facility table {data-navmenu="Clinical Case Management"}  
=====================================  

```{r child=here::here("modules","rmds","8_ccm.Rmd")}
```

Quarantine  {data-orientation=rows}
=====================================  

```{r child=here::here("modules","rmds","9_quarantine.Rmd")}
```
